# Generated by Django 6.1 on 2026-09-26 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('method', models.CharField(max_length=10, verbose_name='HTTP метод')),
                ('path', models.CharField(max_length=500, verbose_name='URL / Эндпоинт')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='HTTP статус ответа')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='Браузер / Клиент')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог запроса',
                'verbose_name_plural': 'Логи запросов',
                'ordering': ['-created_at'],
            },
        ),
    ]
