# Generated by Django 6.1 on 2026-09-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Наприклад: оренда приміщення, придбання канцтоварів', max_length=255, verbose_name='Назва')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Витрата',
                'verbose_name_plural': 'Витрати',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='idx_expense_date')],
            },
        ),
    ]
