# Generated by Django 6.1 on 2026-09-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_options_member_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='payer_type',
            field=models.CharField(choices=[('individual', 'Фізична особа'), ('company', 'Підприємство')], default='individual', max_length=20, verbose_name='Тип особи'),
        ),
    ]
