# Generated by Django 6.1 on 2026-09-14 10:34

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Опис')),
                ('file', models.FileField(upload_to=apps.documents.models.template_upload_path, validators=[apps.documents.models.validate_pdf], verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Завантажено')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблони документів',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('category', models.CharField(choices=[('founding', 'Основний документ'), ('internal', 'Внутрішній документ'), ('protocol', 'Протокол')], db_index=True, max_length=20, verbose_name='Категорія')),
                ('file', models.FileField(upload_to=apps.documents.models.org_document_upload_path, validators=[apps.documents.models.validate_pdf], verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Завантажено')),
            ],
            options={
                'verbose_name': 'Документ ферайну',
                'verbose_name_plural': 'Документи ферайну',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['category', 'uploaded_at'], name='idx_orgdoc_cat_date')],
            },
        ),
    ]
