# Generated by Django 6.1 on 2026-09-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_options_member_created_at_and_more'),
        ('payments', '0003_alter_payment_options_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='idx_payment_date_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_type',
            field=models.CharField(choices=[('individual', 'Фізична особа'), ('company', 'Підприємство'), ('other', 'Інше')], db_index=True, default='individual', max_length=20, verbose_name='Тип платника'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payer_type', 'date'], name='idx_payment_payer_date'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
